name: Manual JS Package Publish

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: "https://registry.npmjs.org"

      - name: Get latest release tag
        id: get-latest-release
        run: |
          LATEST_TAG=$(git tag -l "momoa-js*" --sort=-v:refname | head -n 1)
          echo "latest_tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "Latest tag is $LATEST_TAG"

      - name: Check out latest release
        id: checkout-latest-release
        run: |
          echo 'Checking out release ${{ steps.get-latest-release.outputs.latest_tag }}'
          git checkout ${{ steps.get-latest-release.outputs.latest_tag }}

      - name: Install dependencies
        run: npm install
        working-directory: js

      - name: Build
        run: npm run build
        working-directory: js

      - name: Publish to npm
        run: npm publish --provenance
        working-directory: js
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Generates the social media post
      - run: npx @humanwhocodes/social-changelog --org humanwhocodes --repo momoa --name Momoa --tag ${{ steps.get-latest-release.outputs.latest_tag }} > social-post.txt
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Tweets out release announcement
      - run: 'npx @humanwhocodes/crosspost -t -b -m -l --file social-post.txt'
        env:
            TWITTER_API_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
            TWITTER_API_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
            TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
            TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
            MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
            MASTODON_HOST: ${{ secrets.MASTODON_HOST }}
            BLUESKY_HOST: ${{ vars.BLUESKY_HOST }}
            BLUESKY_IDENTIFIER: ${{ vars.BLUESKY_IDENTIFIER }}
            BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
            LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
